http:
  routers:
    vps-control-room-router:
      rule: Host(`${CONTROL_ROOM_DOMAIN}`)
      service: vps-control-room-service
      middlewares:
        - redirect-to-https
      entryPoints:
        - web
    vps-control-room-router-websecure:
      rule: Host(`${CONTROL_ROOM_DOMAIN}`)
      service: vps-control-room-service
      middlewares:
        - vps-control-room-rate-limit
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
  middlewares:
    vps-control-room-rate-limit:
      rateLimit:
        average: 180
        period: 1m
        burst: 360
  services:
    vps-control-room-service:
      loadBalancer:
        servers:
          - url: http://172.17.0.1:4000
        passHostHeader: true
